name: Check for required files

on:
  push:
    branches: [ update ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check required files
        id: check_required_files
        uses: andstor/file-existence-action@v1
        with:
          files: "update.md"

      - name: Required files exist
        if: steps.check_files.outputs.files_exists != 'true'
        run: |
          echo Required file, 'update.md', is missing
          exit 1
